### ISSUE TITLE
Open issue for translators!

### ISSUE THREAD

**Issue by adi6409** [dogecoinfoundation/foundation.dogecoin.com#14]
In this issue I'll explain how to translate as I have made some changes to the code of the website requiring some modifications to the translation procedure.

At the beginning of the translation process, clone the translators branch of this repository.

the first things you'll have to translate are these strings: 
1. "Dogecoin Foundation"
2. "About the foundation"
3. "News"

After you have those translated correctly, open the config.toml file in a code editor, scroll down to the languages part and copy the part that begins with [languages.en] and ends with an empty line before [languages.fr].
it should look like this:

languages.en]
    title = "Dogecoin Foundation"
    subtitle  = "Hello Friend NG Theme"
    weight    = 1
    baseURL = 'https://foundation.dogecoin.com'
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

don't copy it from this issue, copy it from the code because some issues may occur.

after copying it, paste it after the last language, currently zh. go to the last line of the last language and click enter to create a new line and paste.

edit the languages.en part of the code you just pasted and change the 2 letters "en" to the 2 letters of your language. try googling "(your language here) language code"

modify the title = value in your language to the translation of string 1 from the beginning of this issue.

after that, you are ready to start editing the posts.

I suggest starting with the about page.

you can find all the pages in the content/ folder.

duplicate the page you are willing to translate. IMPORTANT- DUPLICATE THE ONE WITHOUT ANY LANGUAGE CODES. SO IF YOU ARE TRANSLATING THE ABOUT PAGE, DUPLICATE ABOUT.MD, NOT ABOUT.HE.MD.

after duplicating, rename the file to about.xx.md while the about is the page you are translating and xx is your language code, lowercase letters.

translate everything there to your language. and with that, after translating every single page, send a twitter dm to @astroianu and I'll ask you to translate some menu strings which are the last part of the translation.

Every time you start translating, you'll have to pull the changes from GitHub because chances are somebody else pushed some translations while you were away. to do so, open your command line, cd to the git repository folder and do:
`git pull`

after finishing translating a page or a certain part and you want to push it for everyone to see, open your terminal, cd to the git repository folder and do:
`git add *
git commit -m "describe your changes here"
git push -u origin translators`

if you changed something and you want to see it on the website, run the code you have just modified by opening your command line, cd into the git repository folder and run:
`hugo server`

That's it!

**Comment by bobdos** [comment]
Like this?
```
  [languages.zh]
    title = "Dogecoin Foundation"
    subtitle  = "Hello Friend NG Theme"
    baseURL = 'https://foundation.dogecoin.com/zh/'
    weight    = 5
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.zh]
    title = "About Foundation"
    subtitle  = "Hello Friend NG Theme"
    baseURL = 'https://foundation.dogecoin.com/zh/about/'
    weight    = 5
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.zh]
    title = "News"
    subtitle  = "Hello Friend NG Theme"
    baseURL = 'https://foundation.dogecoin.com/zh/posts/'
    weight    = 5
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
```

**Comment by adi6409** [comment]
Like the top one in your comment. The rest are wrong

**Comment by bobdos** [comment]
so where should I put "About Foundation" and "News"? @adi6409

**Comment by bobdos** [comment]
fixed in https://github.com/dogecoinfoundation/foundation.dogecoin.com/blob/main/doc/how-to-translate-website.md
