### ISSUE TITLE
ideas of who should do the final 'merge to main' action after reviewing PASS

### ISSUE THREAD

**Issue by bobdos** [dogecoinfoundation/foundation.dogecoin.com#55]
# Solution 1 - Original Author do the final 'merge to main branch' action

Pros
* If conflict happens, the original author knows how to resolve the conflicts

Cons
* Every contributor needs to be granted access to repo, if more than 100+ translators there...

# Solution 2 - The reviewer do the final 'merge to main branch' action

Pros
* No need to grant every contributor access to repo

Cons
* If conflict happens during merge, the reviewer may have no idea how to resolve the conflict

# Solution 3 - xxx?

---

More ideas or concerns could be raised here, it's an open discussion for everyone.

**Comment by dogespacewizard** [comment]
big noob here
snap just saw this, should i try to revert my merged pr for the kr translations?
