### ISSUE TITLE
If I submit a Simplified Chinese translation, should I put "zh" or "zh_cn" or "zh-cn" or "zh-CN" in the translated file name?

### ISSUE THREAD

**Issue by bobdos** [dogecoinfoundation/foundation.dogecoin.com#8]
If I submit a Simplified Chinese translation, should I put "zh" or "zh_cn" or "zh-cn" or "zh-CN" in the translated file name?

**Comment by bobdos** [comment]
start translating...

![image](https://user-images.githubusercontent.com/195643/130451209-7168b686-649b-47f2-a01c-1a709f661ab2.png)

**Comment by Martyornot** [comment]
Hey! As discussed, you can just put .zh and I'll add the .zh-Hant later on when we have someone who can translate to Traditional Chinese. Cheers !
